---

- name: Add Prometheus Helm charts repository
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Prepare a lists of hosts defined by groups
  set_fact:
    targets_os_hosts: "{{ [] if groups['monitor-os'] is undefined else groups['monitor-os'] if groups['monitor-os']|length > 0 else groups['all'] }}"
    targets_icmp_hosts: "{{ [] if groups['monitor-icmp'] is undefined else groups['monitor-icmp'] if groups['monitor-icmp']|length > 0 else groups['all'] }}"

- name: Create a list of targets with node-exporter
  set_fact:
    targets_os: |
      {% for item in targets_os_hosts %}
      - targets: [ '{{ hostvars[item]["ansible_host"] }}:9100' ]
        labels:
          instance: '{{ hostvars[item]["global_sandbox_name"] }}-{{ hostvars[item]["inventory_hostname"] }}'
          sandbox: '{{ hostvars[item]["global_sandbox_name"] }}'
      {% endfor %}

# --- ICMP targets ---

- name: Create a list of targets for icmp monitoring (ansible_host)
  set_fact:
    targets_icmp_ansible_host: |
      {% for item in targets_icmp_hosts %}
      - targets: [ '{{ hostvars[item]["ansible_host"] }}' ]
        labels:
          instance: '{{ hostvars[item]["global_sandbox_name"] }}-{{ hostvars[item]["inventory_hostname"] }}'
          sandbox: '{{ hostvars[item]["global_sandbox_name"] }}'
          target: '{{ hostvars[item]["ansible_host"] }}'
      {% endfor %}

- name: Parse monitored_hosts_icmp group
  set_fact:
    monitored_icmp_targets: "{{ hostvars[item]['targets'] }}"
  loop: "{{ groups['monitored_hosts_icmp'] | default([]) }}"
  register: monitored_icmp_list

- name: Create a list of targets for icmp monitoring (interface)
  set_fact:
    targets_icmp:
      targets: [ "{{ hostvars[item[0]['item']]['ansible_facts'][item[1]['interface']].ipv4.address | default(hostvars[item[0]['item']]['ansible_facts'][item[1]['interface']].ipv4[0].address) }}" ]
      labels:
        instance: '{{ hostvars[item[0]["item"]]["global_sandbox_name"] }}-{{ hostvars[item[0]["item"]]["inventory_hostname"] }}'
        sandbox: '{{ hostvars[item[0]["item"]]["global_sandbox_name"] }}'
        target: "{{ hostvars[item[0]['item']]['ansible_facts'][item[1]['interface']].ipv4.address | default(hostvars[item[0]['item']]['ansible_facts'][item[1]['interface']].ipv4[0].address) }}"
  loop: "{{ monitored_icmp_list.results | default([]) | subelements('ansible_facts.monitored_icmp_targets', skip_missing=True) | selectattr('1.interface', 'defined') | list }}"
  register: target_list_icmp_interface

- name: Create a list of targets for icmp monitoring (address /32 or FQDN)
  set_fact:
    targets_icmp:
      targets: [ "{{ item[1]['address'] | regex_replace('/32$', '') }}" ]
      labels:
        instance: '{{ hostvars[item[0]["item"]]["global_sandbox_name"] }}-{{ hostvars[item[0]["item"]]["inventory_hostname"] }}'
        sandbox: '{{ hostvars[item[0]["item"]]["global_sandbox_name"] }}'
        target: "{{ item[1]['address'] | regex_replace('/32$', '') }}"
  loop: "{{ monitored_icmp_list.results | default([]) | subelements('ansible_facts.monitored_icmp_targets', skip_missing=True) | selectattr('1.address', 'defined') | selectattr('1.address', 'match', '^[^/]+(\/32)?$') | list }}"
  register: target_list_icmp_address_direct

- name: Create a list of targets for icmp monitoring (CIDR subnet)
  set_fact:
    targets_icmp:
      targets: [ "{{ hostvars[item[0]['item']]['ansible_facts'] | dict2items | selectattr('value.ipv4', 'defined') | map(attribute='value.ipv4') | flatten | select('mapping') | selectattr('address', 'ansible.utils.in_network', item[1]['address']) | map(attribute='address') | first }}" ]
      labels:
        instance: '{{ hostvars[item[0]["item"]]["global_sandbox_name"] }}-{{ hostvars[item[0]["item"]]["inventory_hostname"] }}'
        sandbox: '{{ hostvars[item[0]["item"]]["global_sandbox_name"] }}'
        target: "{{ hostvars[item[0]['item']]['ansible_facts'] | dict2items | selectattr('value.ipv4', 'defined') | map(attribute='value.ipv4') | flatten | select('mapping') | selectattr('address', 'ansible.utils.in_network', item[1]['address']) | map(attribute='address') | first }}"
  loop: "{{ monitored_icmp_list.results | default([]) | subelements('ansible_facts.monitored_icmp_targets', skip_missing=True) | selectattr('1.address', 'defined') | rejectattr('1.address', 'match', '^[^/]+(\/32)?$') | list }}"
  register: target_list_icmp_address_cidr

# --- TCP targets ---

- name: Parse monitored_hosts_tcp group
  set_fact:
    monitored_tcp_targets: "{{ hostvars[item]['targets'] }}"
  loop: "{{ groups['monitored_hosts_tcp'] | default([]) }}"
  register: monitored_tcp_list

- name: Create a list of targets for tcp monitoring (interface)
  set_fact:
    targets_tcp:
      targets: [ "{{ hostvars[item[0]['item']]['ansible_facts'][item[1]['interface']].ipv4.address | default(hostvars[item[0]['item']]['ansible_facts'][item[1]['interface']].ipv4[0].address) }}:{{ item[1]['port'] }}" ]
      labels:
        instance: '{{ hostvars[item[0]["item"]]["global_sandbox_name"] }}-{{ hostvars[item[0]["item"]]["inventory_hostname"] }}'
        sandbox: '{{ hostvars[item[0]["item"]]["global_sandbox_name"] }}'
        target: "{{ hostvars[item[0]['item']]['ansible_facts'][item[1]['interface']].ipv4.address | default(hostvars[item[0]['item']]['ansible_facts'][item[1]['interface']].ipv4[0].address) }}:{{ item[1]['port'] }}"
  loop: "{{ monitored_tcp_list.results | default([]) | subelements('ansible_facts.monitored_tcp_targets', skip_missing=True) | selectattr('1.interface', 'defined') | list }}"
  register: target_list_tcp_interface

- name: Create a list of targets for tcp monitoring (address /32 or FQDN)
  set_fact:
    targets_tcp:
      targets: [ "{{ item[1]['address'] | regex_replace('/32$', '') }}:{{ item[1]['port'] }}" ]
      labels:
        instance: '{{ hostvars[item[0]["item"]]["global_sandbox_name"] }}-{{ hostvars[item[0]["item"]]["inventory_hostname"] }}'
        sandbox: '{{ hostvars[item[0]["item"]]["global_sandbox_name"] }}'
        target: "{{ item[1]['address'] | regex_replace('/32$', '') }}:{{ item[1]['port'] }}"
  loop: "{{ monitored_tcp_list.results | default([]) | subelements('ansible_facts.monitored_tcp_targets', skip_missing=True) | selectattr('1.address', 'defined') | selectattr('1.address', 'match', '^[^/]+(\/32)?$') | list }}"
  register: target_list_tcp_address_direct

- name: Create a list of targets for tcp monitoring (CIDR subnet)
  set_fact:
    targets_tcp:
      targets: [ "{{ hostvars[item[0]['item']]['ansible_facts'] | dict2items | selectattr('value.ipv4', 'defined') | map(attribute='value.ipv4') | flatten | select('mapping') | selectattr('address', 'ansible.utils.in_network', item[1]['address']) | map(attribute='address') | first }}:{{ item[1]['port'] }}" ]
      labels:
        instance: '{{ hostvars[item[0]["item"]]["global_sandbox_name"] }}-{{ hostvars[item[0]["item"]]["inventory_hostname"] }}'
        sandbox: '{{ hostvars[item[0]["item"]]["global_sandbox_name"] }}'
        target: "{{ hostvars[item[0]['item']]['ansible_facts'] | dict2items | selectattr('value.ipv4', 'defined') | map(attribute='value.ipv4') | flatten | select('mapping') | selectattr('address', 'ansible.utils.in_network', item[1]['address']) | map(attribute='address') | first }}:{{ item[1]['port'] }}"
  loop: "{{ monitored_tcp_list.results | default([]) | subelements('ansible_facts.monitored_tcp_targets', skip_missing=True) | selectattr('1.address', 'defined') | rejectattr('1.address', 'match', '^[^/]+(\/32)?$') | list }}"
  register: target_list_tcp_address_cidr

# --- HTTP targets ---

- name: Create a list of targets for http monitoring
  set_fact:
    targets_http: |
      {% for item in monitoring_http_targets | default([]) %}
      - targets: [ "{{ item['url'] }}" ]
        labels:
          instance: "{{ item['url'] }}"
          sandbox: "{{ global_sandbox_name }}"
          __param_module: "{{ 'http_2xx_check_' + (item.check_string | hash('md5')) if item.check_string is defined else 'http_2xx' }}"
      {% endfor %}

# --- Build scrape configs ---

- name: Create scrapeConfigs
  set_fact:
    scrapeConfigs:
      - job_name: "sandbox-{{ global_sandbox_allocation_unit_id }}"
        metrics_path: "/metrics"
        static_configs: "{{ target_list_os.results | map(attribute='ansible_facts.targets_os') | list }}"
        relabel_configs: "{{ custom_os_relabel_configs }}"
        metric_relabel_configs: "{{ custom_os_metric_relabel_configs }}"
      - job_name: "blackbox-icmp-sandbox-{{ global_sandbox_allocation_unit_id }}"
        metrics_path: "/probe"
        scrape_timeout: "15s"
        scrape_interval: "15s"
        params:
          module: [ icmp ]
        static_configs: "{{ (
            target_list_icmp_interface.results | default([]) +
            target_list_icmp_address_direct.results | default([]) +
            target_list_icmp_address_cidr.results | default([])
          ) | map(attribute='ansible_facts.targets_icmp') | list +
          targets_icmp_ansible_host | from_yaml | default([]) }}"
        relabel_configs:
          - source_labels: [ __address__ ]
            target_label: __param_target
          - target_label: __address__
            replacement: prometheus-blackbox-exporter:9115
      - job_name: "blackbox-tcp-sandbox-{{ global_sandbox_allocation_unit_id }}"
        metrics_path: "/probe"
        scrape_timeout: "15s"
        scrape_interval: "15s"
        params:
          module: [ tcp ]
        static_configs: "{{ (
            target_list_tcp_interface.results | default([]) +
            target_list_tcp_address_direct.results | default([]) +
            target_list_tcp_address_cidr.results | default([])
          ) | map(attribute='ansible_facts.targets_tcp') | list }}"
        relabel_configs:
          - source_labels: [ __address__ ]
            target_label: __param_target
          - target_label: __address__
            replacement: prometheus-blackbox-exporter:9115
      - job_name: "blackbox-http-sandbox-{{ global_sandbox_allocation_unit_id }}"
        metrics_path: "/probe"
        scrape_timeout: "15s"
        scrape_interval: "15s"
        static_configs: "{{ targets_http | from_yaml | default([]) }}"
        relabel_configs:
          - source_labels: [ __address__ ]
            target_label: __param_target
          - source_labels: [ __param_module ]
            target_label: __param_module
          - target_label: __address__
            replacement: prometheus-blackbox-exporter:9115

- name: Merge scrapeConfigs with customScrapeConfigs
  set_fact:
    additionalScrapeConfigs: "{{ scrapeConfigs | community.general.lists_mergeby(customScrapeConfigs, 'job_name') }}"

- name: Deploy prometheus
  kubernetes.core.helm:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    name: prometheus
    chart_ref: prometheus-community/kube-prometheus-stack
    chart_version: 72.5.2
    release_namespace: prometheus
    wait: True
    atomic: True
    update_repo_cache: True
    create_namespace: True
    values:
      alertmanager:
        enabled: false
      grafana:
        enabled: false
      prometheus:
        service:
          type: LoadBalancer
        prometheusSpec:
          maximumStartupDurationSeconds: 600
          additionalScrapeConfigs: "{{ additionalScrapeConfigs }}"
  register: result
  retries: 5
  delay: 10
  until: result is not failed
